### ISSUE TITLE
name of package does not agree with name of package in the README

### ISSUE THREAD

**Issue by jlapeyre** [Moelf/JLFzf.jl#1]
The readme uses just `Fzf`

**Comment by Moelf** [comment]
good catch

**Comment by Wikunia** [comment]
Maybe it should be called Fzf ? JL probably stands for julia. This might fall into category 2 here:
https://julialang.github.io/Pkg.jl/v1/creating-packages/#Package-naming-guidelines-1

**Comment by Moelf** [comment]
I agree, but considering there can be a julia implementation of `fzf`, I don't know what to call, maybe not having a package and juts use `fzf_jll` is fine
