### ISSUE TITLE
argument list too long (E2BIG)

### ISSUE THREAD

**Issue by denius** [Moelf/JLFzf.jl#2]
On command
```julia
using JLFzf
JLFzf.inter_fzf(JLFzf.read_repl_hist())
```
I'd the error message `argument list too long (E2BIG)`.

As far as I understand it is a system message -- the created pipe is too long (I have a long Julia history -- more than 15k lines).

Are there any possible solutions that prevent from truncating the output of `JLFzf.read_repl_hist()`?

**Comment by Moelf** [comment]
So, I think on top of the pipe limit, there's also a `Fzf` size limit -- which cannot be bypassed. I'm not 100% sure

**Comment by denius** [comment]
Ok, I see. Anyway, with the truncated list it works:
```julia
JLFzf.inter_fzf(view(JLFzf.read_repl_hist(), 1:5000))
```
