### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by KristofferC** [Moelf/JLFzf.jl#7]
As I described in https://github.com/KristofferC/OhMyREPL.jl/pull/210#issuecomment-684756975 it seems there are some issues when pasting back the code into the REPL on Windows.

**Comment by Moelf** [comment]
Thx for the issue. I will check once I'm on a Windows machine ;)

**Comment by Moelf** [comment]
@denius can you chim in on this if you have time? I was thinking we can re-use more of the code that the stdlib `REPL` use:
https://github.com/JuliaLang/julia/blob/294e5ae423706bc345dd303ffe3ff4e4655f708c/stdlib/REPL/src/LineEdit.jl#L1926
https://github.com/JuliaLang/julia/blob/294e5ae423706bc345dd303ffe3ff4e4655f708c/stdlib/REPL/src/LineEdit.jl#L1688

**Comment by Moelf** [comment]
@KristofferC I have pushed a temporary fix (refresh the line) so at least users don't see a black line.

**Comment by Moelf** [comment]
should be fixed now: https://github.com/Moelf/JLFzf.jl/commit/d4c4b0726b69e92daf2bd9f464a3ea6cc7014d64
